### ISSUE TITLE
'Featured Images' are not sent to template on single view pages with a 'feaured image' set.

### ISSUE THREAD

**Issue by julianstr** [ErinMorelli/em-beer-manager#7]
The featured image works properly within the EMBeer Module, However in the same step it 'steals' the featured image from the rest of the template. An example is in the header image with the twentyseventeen theme from WP. 

there is no header image if a featured image is set:

http://new.appleblossombrewing.com/beers/barrel-aged-tripel/

this issue is only present when using the featured image, which definitely enhances the menu/layout greatly. 
Also, if there is not a featured image set it goes back to template default header image and the individual beer page looks normal. 

http://new.appleblossombrewing.com/beers/bella-glos-meiomi-pinot-noir/

Thanks for designing such a cool plugin.
If you suspect the issue is on template side, not plugin, please let me know.

**Comment by ErinMorelli** [comment]
Hi @julianstr! Thanks for reporting this - I'll be taking a look into it this week and I'll get back to you with what I find!

**Comment by ErinMorelli** [comment]
Hi @julianstr - I looked into this and it looks like it's an issue with the theme you're using "Five Hacks For TwentySeventeen". If you look at this line of the code for the theme:
https://github.com/jpen365/five-hacks-for-twenty-seventeen/blob/master/header.php#L39

You can see that the theme is attempting to load the featured image for the beer as the header image on beer pages, instead of the theme's own header image. This seems like something that should be an option to override within the theme, so I would definitely ask the theme's author about it!

Hope this helps! Definitely let me know if you run into any more issues!
